language: java
sudo: false # faster builds

jdk:
    - oraclejdk8
    - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
