language: java
sudo: false

jdk:
  - oraclejdk8
  - openjdk7

cache:
  directories:
    - $HOME/.m2
    - $HOME/.m2/wrapper

install: true

script:
  - travis_wait 30 ./mvnw --batch-mode --no-transfer-progress clean install -DskipTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)