name: Integration test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare dependencies
        run: ./mvnw clean install -DskipTests=true -Drevision=PR-${{ github.sha	}}

      - name: Clean workspace
        run: rm -rf dubbo-samples

      - name: Checkout dubbo-samples
        run: git clone https://github.com/apache/dubbo-samples.git

      - name: Prepare integration
        run: cd dubbo-samples && ./mvnw -U --batch-mode --no-transfer-progress --settings .mvn/settings.xml clean install -pl dubbo-maven-address-plugin -Ddubbo.version=PR-${{ github.sha	}}

      - name: Run integration test
        run: cd dubbo-samples && ./mvnw -U --batch-mode --no-transfer-progress --settings .mvn/settings.xml clean verify -Pdubbo-integration-test -Djava-image.name=openjdk:8 -Ddubbo.version=PR-${{ github.sha }}


